### ISSUE TITLE
Ensure ownership of the buildings to the player hero that builds them

### ISSUE THREAD

**Issue by MNoya** [Myll/Dota-2-Building-Helper#10]
Building created doesn't have ownership on the hero, preventing it from casting abilities with gold cost.

**Comment by Myll** [comment]
Make sure you do ["CasterCanControl"  "1"](https://github.com/Myll/Dota-2-Building-Helper/blob/master/game/dota_addons/samplerts/scripts/npc/npc_abilities_custom.txt#L22) in KV. I changed the default behavior to get the pID from the player's hero rather than the caster like in the other issue.

Or in the [OnConstructionStarted](https://github.com/Myll/Dota-2-Building-Helper/blob/master/game/dota_addons/samplerts/scripts/vscripts/abilities.lua#L3) you can do your own SetControllableByPlayer stuff
