### ISSUE TITLE
read me is a little bit not complete

### ISSUE THREAD

**Issue by AeroHand** [Myll/Dota-2-Building-Helper#32]
didnt include require('util')
also every string for require should not have .lua extension

**Comment by AeroHand** [comment]
also the build function and addbuilding function is not as ez to read and change as the previous version did... i would take some time to read through all your code :)

**Comment by Myll** [comment]
Util shouldn't no longer be required to use BH. All the util funcs are in
Buildinghelper.lua. I will remove the .lua from requires.

didnt include require('util')
also every string for require should not have .lua extension

—
Reply to this email directly or view it on GitHub
<https://github.com/Myll/Dota-2-Building-Helper/issues/32>.

**Comment by AeroHand** [comment]
actually in buildinghelper.lua
in the init part, u called initabilities functions in util.

**Comment by AeroHand** [comment]
also r there any ways i could restrict one specific player to build buildings in one area?

**Comment by Myll** [comment]
oh ok, i will add that function to buildinghelper.lua

you could if you change the code :p. You need to change the BUILDING_SQUARES table to be in the player handle instead of global. and `BuildingHelper:CloseSquares` and `BuildingHelper:OpenSquares` should take the player handle as another parameter.

**Comment by AeroHand** [comment]
sure. glad i could be a contributor!
